---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-6"
    config: "./.eslintrc.json"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.module"
exclude_paths: []
